### ISSUE TITLE
The Operator injected with proxy failed to start.

### ISSUE THREAD

**Issue by qiuming520** [KusionStack/controller-mesh#32]
## General Question
**My Operator : [mysql-operator](https://github.com/bitpoke/mysql-operator)
k8s version : v1.21.5
controller-mesh : v0.1.2
shardingconfig-root :**
```yaml
apiVersion: ctrlmesh.kusionstack.io/v1alpha1
kind: ShardingConfig
metadata:
  name: sharding-root
  namespace: test-mysql
spec:
  root:
    prefix: mysql-operator
    targetStatefulSet: mysql-operator
    canary:
      replicas: 1
      inNamespaces:
      - demo-0a
      - demo-0b
      - demo-0c
    auto:
      everyShardReplicas: 2
      shardingSize: 2
    resourceSelector:
    - relateResources:
      - apiGroups:
        - '*'
        resources:
        - '*'
  controller:
    leaderElectionName: mysql-operator-leader-election
```
My Operator has 2 containers (operator and orchestrator). When not using patch to add the labels required by ctrlmesh (ctrlmesh.kusionstack.io/enable-proxy: "true", ctrlmesh.kusionstack.io/watching: "true") , can be started successfully. After using patch to request labeling, ctrlmesh-proxy and operator can start normally, but orchestrator fails to start with the following error:
```shell
Error starting command: `--kubeconfig=/etc/kubernetes/kubeconfig/fake-kubeconfig.yaml` - fork/exec --kubeconfig=/etc/kubernetes/kubeconfig/fake-kubeconfig.yaml: no such file or directory
```
`kubectl get  pod/mysql-operator-0 -oyaml` Check the pod and find that the `/etc/kubernetes/kubeconfig/fake-kubeconfig.yaml` file has been mounted

**Who can help me?**

**Comment by Eikykun** [comment]
Thx for your report, @qiuming520 

Please check:
- Whether the configmap named `fake-kubeconfig` has been automatically created in namespace `test-mysql`;
- Whether the file `/etc/kubernetes/kubeconfig/fake-kubeconfig.yaml` exists in the container directory.

If none of the above issues have occurred, I may need more information, such as the complete pod yaml, pod events, etc.

**Comment by qiuming520** [comment]
> Thx for your report, @qiuming520
> 
> Please check:
> 
> * Whether the configmap named `fake-kubeconfig` has been automatically created in namespace `test-mysql`;
> * Whether the file `/etc/kubernetes/kubeconfig/fake-kubeconfig.yaml` exists in the container directory.
> 
> If none of the above issues have occurred, I may need more information, such as the complete pod yaml, pod events, etc.

@Eikykun  

- cm (named fake-kubeconfig)  already exists
![image](https://github.com/KusionStack/controller-mesh/assets/10718885/fde99187-5121-465f-900d-368baf000cb1)

- My Operator has 2 containers  (operator and orchestrator).  For the operator container that started successfully, I can  the file `/etc/kubernetes/kubeconfig/fake-kubeconfig.yaml`.  For the orchestrator container that failed to start, it is impossible to enter the inside of the container, so it is impossible to view the internal files. I have tried to manually mount the `/etc/kubernetes/kubeconfig/fake-kubeconfig.yaml` into My Operator without injecting ctrlmesh-proxy, and it can be started successfully, and both have `/etc/kubernetes/kubeconfig/fake-kubeconfig.yaml` . After injecting ctrlmesh-proxy,  orchestrator failed to start

**Comment by qiuming520** [comment]
> Thx for your report, @qiuming520
> 
> Please check:
> 
> * Whether the configmap named `fake-kubeconfig` has been automatically created in namespace `test-mysql`;
> * Whether the file `/etc/kubernetes/kubeconfig/fake-kubeconfig.yaml` exists in the container directory.
> 
> If none of the above issues have occurred, I may need more information, such as the complete pod yaml, pod events, etc.

this is My Operator's pod 
```yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      checksum/orchestrator-config: 2e45145f5b5bb11a0f82027015b5fd76d661bfea6b05ba68adae09df886eff93
      checksum/orchestrator-secret: 508297128b9dc867611b9f1339e035f090c7fdbf9f4a3abb9e57b6c4b6680508
      cni.projectcalico.org/containerID: 62603afe25757219694bb42dd8d22570040690ccb5756f3a3a62b9dd0cfdbf09
      cni.projectcalico.org/podIP: 10.xx.xx.62/32
      cni.projectcalico.org/podIPs: 10.xx.xx.62/32,fd33:xx.xx:e03e/128
    creationTimestamp: "2024-02-05T11:14:55Z"
    generateName: mysql-operator-
    labels:
      app.kubernetes.io/instance: mysql-operator
      app.kubernetes.io/name: mysql-operator
      controller-revision-hash: mysql-operator-75fd7f67b9
      ctrlmesh.kusionstack.io/control: "true"
      ctrlmesh.kusionstack.io/enable-proxy: "true"
      ctrlmesh.kusionstack.io/namespace: test-mysql
      ctrlmesh.kusionstack.io/shard-hash: "3"
      ctrlmesh.kusionstack.io/sharding-config-injected: mysql-operator-0-canary
      ctrlmesh.kusionstack.io/watching: "true"
      statefulset.kubernetes.io/pod-name: mysql-operator-0
    name: mysql-operator-0
    namespace: test-mysql
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: StatefulSet
      name: mysql-operator
      uid: 23342e03-437d-4937-8c27-cff333dbb6f5
    resourceVersion: "15311632"
    uid: b9b5b80c-0b20-4527-ab29-65a2f5c549d3
  spec:
    containers:
    - args:
      - --leader-election-name=mysql-operator-leader-election
      env:
      - name: POD_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.namespace
      - name: POD_IP
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: status.podIP
      image: xxx/cnp/kusionstack/ctrlmesh-proxy:v0.1.2
      imagePullPolicy: IfNotPresent
      lifecycle:
        postStart:
          exec:
            command:
            - /bin/sh
            - -c
            - /poststart.sh
      name: ctrlmesh-proxy
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /readyz
          port: 5441
          scheme: HTTP
        periodSeconds: 3
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 100m
          ephemeral-storage: 2Gi
          memory: 100Mi
        requests:
          cpu: 100m
          ephemeral-storage: 2Gi
          memory: 100Mi
      securityContext:
        privileged: true
        runAsUser: 1359
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-drm8w
        readOnly: true
    - args:
      - --leader-election-namespace=test-mysql
      - --orchestrator-uri=http://mysql-operator.test-mysql/api
      - --sidecar-image=xxxcnp/bitpoke/mysql-operator-sidecar-5.7:v0.6.3
      - --sidecar-mysql8-image=xxx/cnp/bitpoke/mysql-operator-sidecar-8.0:latest
      - --metrics-exporter-image=xxx/cnp/prom/mysqld-exporter:v0.13.0
      - --failover-before-shutdown=true
      - --kubeconfig=/etc/kubernetes/kubeconfig/fake-kubeconfig.yaml
      env:
      - name: ORC_TOPOLOGY_USER
        valueFrom:
          secretKeyRef:
            key: TOPOLOGY_USER
            name: mysql-operator-orc
      - name: ORC_TOPOLOGY_PASSWORD
        valueFrom:
          secretKeyRef:
            key: TOPOLOGY_PASSWORD
            name: mysql-operator-orc
      - name: KUBECONFIG
        value: /etc/kubernetes/kubeconfig/fake-kubeconfig.yaml
      image: xxx/cnp/bitpoke/mysql-operator:v0.6.3
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /healthz
          port: 8081
          scheme: HTTP
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      name: operator
      ports:
      - containerPort: 8080
        name: prometheus
        protocol: TCP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /readyz
          port: 8081
          scheme: HTTP
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources: {}
      securityContext: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-drm8w
        readOnly: true
      - mountPath: /etc/kubernetes/kubeconfig
        name: fake-kubeconfig
        readOnly: true
    - args:
      - --kubeconfig=/etc/kubernetes/kubeconfig/fake-kubeconfig.yaml
      env:
      - name: POD_IP
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: status.podIP
      - name: KUBECONFIG
        value: /etc/kubernetes/kubeconfig/fake-kubeconfig.yaml
      envFrom:
      - prefix: ORC_
        secretRef:
          name: mysql-operator-orc
      image: xxx/cnp/bitpoke/mysql-operator-orchestrator:v0.6.3
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /api/lb-check
          port: 3000
          scheme: HTTP
        initialDelaySeconds: 200
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 10
      name: orchestrator
      ports:
      - containerPort: 3000
        name: http
        protocol: TCP
      - containerPort: 10008
        name: raft
        protocol: TCP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /api/raft-health
          port: 3000
          scheme: HTTP
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 10
      resources: {}
      securityContext: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/lib/orchestrator
        name: data
      - mountPath: /usr/local/share/orchestrator/templates
        name: config
      - mountPath: /etc/kubernetes/kubeconfig
        name: fake-kubeconfig
        readOnly: true
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-drm8w
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    hostname: mysql-operator-0
    nodeName: kcs-operator-mesh-s-cqngs
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext:
      fsGroup: 65532
      runAsGroup: 65532
      runAsNonRoot: true
      runAsUser: 65532
    serviceAccount: mysql-operator
    serviceAccountName: mysql-operator
    subdomain: mysql-operator-orc
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 240
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 240
    volumes:
    - configMap:
        defaultMode: 420
        name: fake-kubeconfig
      name: fake-kubeconfig
    - configMap:
        defaultMode: 420
        name: mysql-operator-orc
      name: config
    - emptyDir: {}
      name: data
    - name: kube-api-access-drm8w
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2024-02-05T11:14:55Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2024-02-05T11:14:55Z"
      message: 'containers with unready status: [orchestrator]'
      reason: ContainersNotReady
      status: "False"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2024-02-05T11:14:55Z"
      message: 'containers with unready status: [orchestrator]'
      reason: ContainersNotReady
      status: "False"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2024-02-05T11:14:55Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://bc122c413a4c436b260456d100ffd4a477ae34d3f54ac7983f7a84ef96d7fc6f
      image: xxx/cnp/kusionstack/ctrlmesh-proxy:v0.1.2
      imageID: xxx/cnp/kusionstack/ctrlmesh-proxy@sha256:50afae553649cdf57b0182fb3693d93902e9f6f7830ae588ea19d69ee1aee9c9
      lastState: {}
      name: ctrlmesh-proxy
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2024-02-05T11:14:55Z"
    - containerID: containerd://8ac364315ff100fe95aa4c6636aca5cd221d922da4fea0fb01327f2e39fe1376
      image: xxx/cnp/bitpoke/mysql-operator:v0.6.3
      imageID: xxx/cnp/bitpoke/mysql-operator@sha256:0076da68c4aa7a845f5e7e7b9f26c5765d3a9aee339ca39d686663b764a4cd26
      lastState: {}
      name: operator
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2024-02-05T11:14:58Z"
    - containerID: containerd://adb84258961d9256bf8ccd25677cb77efc8b8a5b4da984fb1190ee59a95bde9d
      image: xxx/cnp/bitpoke/mysql-operator-orchestrator:v0.6.3
      imageID: xxx/cnp/bitpoke/mysql-operator-orchestrator@sha256:49b6c3e06b02c970382d7a0f1e6079ee211bab1504ea97214a059f49d247e883
      lastState:
        terminated:
          containerID: containerd://adb84258961d9256bf8ccd25677cb77efc8b8a5b4da984fb1190ee59a95bde9d
          exitCode: 1
          finishedAt: "2024-02-05T12:11:44Z"
          reason: Error
          startedAt: "2024-02-05T12:11:44Z"
      name: orchestrator
      ready: false
      restartCount: 16
      started: false
      state:
        waiting:
          message: back-off 5m0s restarting failed container=orchestrator pod=mysql-operator-0_test-mysql(b9b5b80c-0b20-4527-ab29-65a2f5c549d3)
          reason: CrashLoopBackOff
    hostIP: 192.168.0.217
    phase: Running
    podIP: 10.12.224.62
    podIPs:
    - ip: 10.12.224.62
    - ip: fd33:1111:2222:4da8:56ad:5fb6:afcc:e03e
    qosClass: Burstable
    startTime: "2024-02-05T11:14:55Z"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by wu8685** [comment]
> > Thx for your report, @qiuming520
> > Please check:
> > 
> > * Whether the configmap named `fake-kubeconfig` has been automatically created in namespace `test-mysql`;
> > * Whether the file `/etc/kubernetes/kubeconfig/fake-kubeconfig.yaml` exists in the container directory.
> > 
> > If none of the above issues have occurred, I may need more information, such as the complete pod yaml, pod events, etc.
> 
> this is My Operator's pod [mysql-operator.txt](https://github.com/KusionStack/controller-mesh/files/14165675/mysql-operator.txt)

Can you provide the last log of the orchestrator container when it failed to start with ctrlmesh-proxy injected. You can find it by command `kubectl logs pod <your-operator-pod-name> -c orchestrator -p`.

**Comment by qiuming520** [comment]
> > > Thx for your report, @qiuming520
> > > Please check:
> > > 
> > > * Whether the configmap named `fake-kubeconfig` has been automatically created in namespace `test-mysql`;
> > > * Whether the file `/etc/kubernetes/kubeconfig/fake-kubeconfig.yaml` exists in the container directory.
> > > 
> > > If none of the above issues have occurred, I may need more information, such as the complete pod yaml, pod events, etc.
> > 
> > 
> > this is My Operator's pod [mysql-operator.txt](https://github.com/KusionStack/controller-mesh/files/14165675/mysql-operator.txt)
> 
> Can you provide the last log of the orchestrator container when it failed to start with ctrlmesh-proxy injected. You can find it by command `kubectl logs pod <your-operator-pod-name> -c orchestrator -p`.
 
this is log
![image](https://github.com/KusionStack/controller-mesh/assets/10718885/c5e480a9-cd03-4e71-96b0-5263b00e19fa)

**Comment by Eikykun** [comment]
The `orchestrator`'s operator process might not have permissions to read `/etc/kubernetes/kubeconfig/fake-kubeconfig.yaml`. You can try removing the `securityContext` from the pod and start the manager process inside the container `orchestrator` with root privileges to troubleshoot this issue. @qiuming520

**Comment by qiuming520** [comment]
> You can try removing the `securityContext` from the pod and start the manager process inside the container `orchestrator` with root privileges to troubleshoot this issue

I have added securityContext for my containers (operator and orchestrator). 
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-operator
  namespace: test-mysql-1
spec:
  template:
  ... ...
    spec:
      containers:
      - name: operator
        securityContext:
          privileged: true
  ... ...
      - name: orchestrator
        securityContext:
          privileged: true
  ... ...
      securityContext: {}
  ... ...
```
As you can see in the picture below, the file `（/etc/kubernetes/kubeconfig/fake-kubeconfig.yaml）` exists and has root privileges in operator container.
![image](https://github.com/KusionStack/controller-mesh/assets/10718885/13c112af-af97-4189-a148-f9800cc54b81)

But the issue still exists~ @Eikykun

**Comment by Eikykun** [comment]
I tried to reproduce this issue using two sample operator containers, but was not successful.  Can you provide a scenario that reproduces this issue in kind? @qiuming520

**Comment by qiuming520** [comment]
> I tried to reproduce this issue using two sample operator containers, but was not successful. Can you provide a scenario that reproduces this issue in kind?

of course ！ my Operator github [https://github.com/bitpoke/mysql-operator](https://github.com/bitpoke/mysql-operator)

my scenario：Some pods use the canary namespace, and some pods use the normally released namespace. 
**shardingconfig-root :**
```yaml
apiVersion: ctrlmesh.kusionstack.io/v1alpha1
kind: ShardingConfig
metadata:
  name: sharding-root
  namespace: test-mysql-1
spec:
  root:
    prefix: mysql-operator
    targetStatefulSet: mysql-operator
    canary:
      replicas: 1
      inNamespaces:
      - mysql-01
      - mysql-02
      - mysql-03
    auto:
      everyShardReplicas: 1
      shardingSize: 1
    resourceSelector:
    - relateResources:
      - apiGroups:
        - '*'
        resources:
        - '*'
  controller:
    leaderElectionName: mysql-operator-leader-election
```

**Comment by Eikykun** [comment]
> > I tried to reproduce this issue using two sample operator containers, but was not successful. Can you provide a scenario that reproduces this issue in kind?
> 
> of course ！ my Operator github https://github.com/bitpoke/mysql-operator
> 
> my scenario：Some pods use the canary namespace, and some pods use the normally released namespace. **shardingconfig-root :**
> 
> ```yaml
> apiVersion: ctrlmesh.kusionstack.io/v1alpha1
> kind: ShardingConfig
> metadata:
>   name: sharding-root
>   namespace: test-mysql-1
> spec:
>   root:
>     prefix: mysql-operator
>     targetStatefulSet: mysql-operator
>     canary:
>       replicas: 1
>       inNamespaces:
>       - mysql-01
>       - mysql-02
>       - mysql-03
>     auto:
>       everyShardReplicas: 1
>       shardingSize: 1
>     resourceSelector:
>     - relateResources:
>       - apiGroups:
>         - '*'
>         resources:
>         - '*'
>   controller:
>     leaderElectionName: mysql-operator-leader-election
> ```

I briefly looked at the `orchestrator` container, and it seems that it may not be a standard operator implemented using `controller-runtime`, as it does not use the `--kubeconfig` argument. Here, it may be necessary to understand the operating logic of the `orchestrator` container. If there is a case where a container is not an operator, it might require additional support from a new version.

**Comment by qiuming520** [comment]
> > > I tried to reproduce this issue using two sample operator containers, but was not successful. Can you provide a scenario that reproduces this issue in kind?
> > 
> > 
> > of course ！ my Operator github https://github.com/bitpoke/mysql-operator
> > my scenario：Some pods use the canary namespace, and some pods use the normally released namespace. **shardingconfig-root :**
> > ```yaml
> > apiVersion: ctrlmesh.kusionstack.io/v1alpha1
> > kind: ShardingConfig
> > metadata:
> >   name: sharding-root
> >   namespace: test-mysql-1
> > spec:
> >   root:
> >     prefix: mysql-operator
> >     targetStatefulSet: mysql-operator
> >     canary:
> >       replicas: 1
> >       inNamespaces:
> >       - mysql-01
> >       - mysql-02
> >       - mysql-03
> >     auto:
> >       everyShardReplicas: 1
> >       shardingSize: 1
> >     resourceSelector:
> >     - relateResources:
> >       - apiGroups:
> >         - '*'
> >         resources:
> >         - '*'
> >   controller:
> >     leaderElectionName: mysql-operator-leader-election
> > ```
> 
> I briefly looked at the `orchestrator` container, and it seems that it may not be a standard operator implemented using `controller-runtime`, as it does not use the `--kubeconfig` argument. Here, it may be necessary to understand the operating logic of the `orchestrator` container. If there is a case where a container is not an operator, it might require additional support from a new version.

Thx for your reply to helped me solve confusion~ @Eikykun
